### ISSUE TITLE
Add sun graphic when mailbox is empty 🌤️

### ISSUE THREAD

**Issue by markwaddle** [kallepersson/inboxtheme#36]
one of my favorite features of Inbox was the sun graphic, along with the animation, that shows when your inbox is empty. it's a great reward for getting to inbox zero each day. it would be great to add that to this extension. thanks!

**Comment by markwaddle** [comment]
this is not perfect, but it's an improvement

```css
.TD>.TC {
  background-image: url('https://ssl.gstatic.com/bt/C3341AA7A1A076756462EE2E5CD71C11/zero/2x/ic_zero_inbox_2x.png';
  background-repeat: no-repeat;
  background-position: center;
  height: 500px;
  color: transparent;
}
```
